name: Matrix Demo
on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev/**'
      - 'feature/**'
      - 'release/**'
    paths-ignore:
      - '.github/workflows/**'
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [18.x]
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - node-version: 12.x
            operating-system: ubuntu-latest
          - node-version: 14.x
            operating-system: windows-latest
          - node-version: 18.x
            operating-system: macos-latest
        exclude:
          - node-version: 12.x
            operating-system: ubuntu-latest
    runs-on: ${{ matrix.operating-system }}
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Dependencies
        run: |
          npm install
          npm ci
      - name: Build Project
        run: npm run build